version: "3.6"
services:
  semantic-release:
    image: neowaylabs/semantic-releasedev:latest
    container_name: semantic-release
    links:
     - gitlab

  gitlab:
      image: 'gitlab/gitlab-ee:14.9.2-ee.0'
      container_name: ${GITLAB_CONTAINER_NAME}
      restart: always
      hostname: 'gitlab'
      environment:
        GITLAB_OMNIBUS_CONFIG: |
          external_url 'https://gitlab.com';        
          gitlab_rails['initial_root_password'] = "password";   
          # the default root username is 'root'
          # Add any other gitlab.rb configuration here, each on its own line
      ports:
        - '80:80'
        - '443:443'
        - '3022:22'
      shm_size: '256m'
